### ISSUE TITLE
Channel Link

### ISSUE THREAD

**Issue by maddinq** [brrrrrrrt/brt_videourlreplace#1]
How can I set a link to a channel..without your thumbnail generation ? ..can I add a class or anything that it don't adds a iframe etc. ?

**Comment by brrrrrrrt** [comment]
the easiest "workaround" is like this: 
You add a page to the TYPO3 tree of the type "external link" (set it hidden in menus) and put in your channel URL. 
In the TYPO3 Link Wizard you just select the Page instead of the external URL.
Now you have a URL like http://yoursite.com/mychannel which redirects to your Channel. 

And as a "special" feature of this solution, you will see all your visitors clicks to the channel URL in your websites statistics.

I know this solution maybe only be acceptable if you do not have lots of channel you want to link to, i will make a proper solution in a future release.

**Comment by maddinq** [comment]
Hey, I have more than 10 of this links. And have also a good event-handling via google analytics ..so this solutions isn't cool for me ;) ...hope to get a better solution from you soon. Really like the idea of you extensions..because I developed a own solution. Little bit different..

**Comment by brrrrrrrt** [comment]
ok, i pushed a new release (v1.0.9) to the TYPO3 Extension Repository, it now ignores URLs if it contains certain stopwords (channel,user,playlist) like https://www.youtube.com/channel/UCGBpxWJr9FNOcFYA5GkKrMg or https://www.youtube.com/user/Jokerkhk 

does this solution work for you?

**Comment by maddinq** [comment]
Hey, it will work for youtube ..but not for vimeo links like (https://vimeo.com/slingshotkite or https://vimeo.com/slingshotwake). Any idea ?

**Comment by brrrrrrrt** [comment]
is fixed in latest version 1.1.0, should hit the repos soon - now uses vimeo and dailymotion API to check if its a link to a video

**Comment by maddinq** [comment]
Hey Robert,

I still have a strange behaviour in the footer... please mouse over the VIMEO and YOUTUBE links in the footer -> http://www.slingshotsports.de/

**Comment by brrrrrrrt** [comment]
i am sorry i cant see any problem, what exactly do you mean?

**Comment by maddinq** [comment]
Sorry I had to deactivate the extension again. For some reason it changed the look of the icons again. I have to check it later.

**Comment by brrrrrrrt** [comment]
ok, i see, you are using the classes "vimeo" and "youtube".  the extension also uses this classes for the background-resize effect of the thumbnails.

you should be able to deactivate this behavioour by adding this to your css:

.youtube:hover, .vimeo:hover, .dailymotion:hover {
	background-size: 100% !important;
}

**Comment by brrrrrrrt** [comment]
i think the classes "vimeo", "youtube" and "dailymotion" may be just too common, i will change the classnames to something like "vimeo-vurpl" etc. in the next release.
